
AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: A Nodejs Package Lambda Layer .
Parameters:
  ProjectName:
    Type: String
    Default: mpr
  LayerName:
    Type: String
  LayerDescription:
    Type: String
  EnvType:
    Type: String
    Default: prod
Resources:
  libs:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Join ["-", [!Ref ProjectName, !Ref EnvType, !Ref LayerName]]
      Description: !Ref LayerDescription
      ContentUri: lib/.
      CompatibleRuntimes:
        - nodejs12.x  
        - nodejs14.x  
        - nodejs16.x  
Outputs:
  LambdaLayer:
    Value: !Ref libs
    Export:
      Name: !Join ["-", [!Ref ProjectName, !Ref EnvType, layer, !Ref LayerName]]    
    